---
name: tests
on: [ push, pull_request ]
jobs:
  test:
    name: Test (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install libexiv2-dev
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --quiet --yes --no-install-recommends libexiv2-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rake spec
